# Generated by Django 4.0.6 on 2022-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjeta',
            fields=[
                ('marcaid', models.AutoField(db_column='marcaID', primary_key=True, serialize=False)),
                ('tipo_tarjeta', models.TextField()),
            ],
            options={
                'db_table': 'marcas_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.TextField(unique=True)),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('fecha_otorgamiento', models.TextField()),
                ('fecha_expiracion', models.TextField()),
                ('marcaid', models.IntegerField(blank=True, db_column='marcaID', null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
