# Generated by Django 4.1 on 2022-08-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
