# Generated by Django 4.1 on 2022-08-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer_id',
            field=models.ForeignKey(default=282, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
