# Generated by Django 4.1 on 2022-08-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_profile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer_id',
            field=models.ForeignKey(default=499, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
