# Generated by Django 4.1 on 2022-08-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_profile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer_id',
            field=models.IntegerField(blank=True, default=322, null=True),
        ),
    ]
