# Generated by Django 4.1 on 2022-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesPrestamos',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.CharField(max_length=100, verbose_name='monto')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('tipo_prestamo', models.TextField(default='tipo_prestamo', max_length=100, verbose_name='tipo de prestamo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de modificación')),
            ],
        ),
    ]
