# Generated by Django 4.1 on 2022-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebank', '0002_solicitudesprestamos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesprestamos',
            name='tipo_prestamo',
            field=models.CharField(default='tipo_prestamo', max_length=100, verbose_name='tipo de prestamo'),
        ),
        migrations.AlterField(
            model_name='solicitudesprestamos',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
