# Generated by Django 4.1 on 2022-08-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebank', '0003_alter_solicitudesprestamos_tipo_prestamo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudesprestamos',
            old_name='usuario',
            new_name='customer_id',
        ),
    ]
