# Generated by Django 4.0.6 on 2022-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposCuenta',
            fields=[
                ('cuentaid', models.AutoField(db_column='cuentaID', primary_key=True, serialize=False)),
                ('cuenta_cliente', models.TextField()),
            ],
            options={
                'db_table': 'tipos_cuenta',
                'managed': False,
            },
        ),
    ]
